// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVeUilxqbw-li_Y0LeuUHfbuqsSQ-iBs',
    appId: '1:191431395760:web:291f1125f7ba7fd85dee75',
    messagingSenderId: '191431395760',
    projectId: 'chat-bot-ai-e4640',
    authDomain: 'chat-bot-ai-e4640.firebaseapp.com',
    storageBucket: 'chat-bot-ai-e4640.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoqMdnCyOSvOig3JWlPGfL6qVNGXzL-0',
    appId: '1:191431395760:android:49b2baec84b2820b5dee75',
    messagingSenderId: '191431395760',
    projectId: 'chat-bot-ai-e4640',
    storageBucket: 'chat-bot-ai-e4640.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzVeUilxqbw-li_Y0LeuUHfbuqsSQ-iBs',
    appId: '1:191431395760:web:4ad81ac303e48c855dee75',
    messagingSenderId: '191431395760',
    projectId: 'chat-bot-ai-e4640',
    authDomain: 'chat-bot-ai-e4640.firebaseapp.com',
    storageBucket: 'chat-bot-ai-e4640.firebasestorage.app',
  );
}
